# Generated by Django 3.2.7 on 2021-09-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='touristspot',
            table='tour_touristspot',
        ),
    ]
