# Generated by Django 3.2.7 on 2021-09-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_touristspot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='categorydetail',
            field=models.CharField(default=0, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='touristspot',
            table=None,
        ),
    ]
