# Generated by Django 3.2.7 on 2021-09-20 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0003_auto_20210918_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToruistImg',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.CharField(max_length=255)),
                ('Touristspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touristspot')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('Touristspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touristspot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
