# Generated by Django 3.2.7 on 2021-09-20 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_touristspot_counting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristspot',
            name='counting',
            field=models.IntegerField(default=0),
        ),
    ]
