# Generated by Django 3.2.7 on 2021-09-27 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0008_alter_toruistimg_touristspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=125)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routelike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Route_Touristspot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.route')),
                ('touristspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.touristspot')),
            ],
        ),
    ]
