# Generated by Django 3.2.7 on 2021-09-27 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_route_route_touristspot_routelike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='title',
        ),
    ]
