# Generated by Django 3.2.7 on 2021-09-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0011_rename_route_touristspot_routetouristspot'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfield', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
