# Generated by Django 3.2.7 on 2021-09-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0012_auto_20210929_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='toruistimg',
            name='awsimages',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
