# Generated by Django 3.2.7 on 2021-09-16 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='compainion',
            new_name='companion',
        ),
    ]
