# Generated by Django 3.2.7 on 2021-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_compainion_user_companion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authenticated',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.BooleanField(null=True),
        ),
    ]
