# Generated by Django 3.2.7 on 2021-09-23 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210920_1327'),
        ('accounts', '0004_city'),
    ]

    operations = [
    ]
